### ISSUE TITLE
Please make this work for Vis IDE 2019

### ISSUE THREAD

**Issue by Smurf-IV** [kemmis/Kemmis.MyWorkItemsOnPendingChangesPage#21]

**Comment by kemmis** [comment]
new version here: https://marketplace.visualstudio.com/items?itemName=TheRealRafeKemmis.mwivs2019

**Comment by Smurf-IV** [comment]
Please also update your `readme.md`
**And** it is not showing up in the Search:
![image](https://user-images.githubusercontent.com/2418812/56112303-8b44a700-5f52-11e9-89c3-b2210c1f1d7b.png)

**Comment by Smurf-IV** [comment]
> 
> 
> new version here: https://marketplace.visualstudio.com/items?itemName=TheRealRafeKemmis.mwivs2019

That requires a login, The target machine is standalone as is the license.

**Comment by kemmis** [comment]
oh strange. I must have missed a checkbox somewhere. i'm looking into this now.

**Comment by kemmis** [comment]
I just had to make the extension public in the VS marketplace site. It should be there now.
